esphome:
  name: igrill

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://bendikwa/esphome-igrill@v1.0

esp32_ble_tracker:

ble_client:
  - mac_address: 70:91:8F:XX:XX:XX
    id: igrill_device

sensor:
  - platform: igrill
    ble_client_id: igrill_device
    update_interval: 30s # default
    send_value_when_unplugged: true # default
    unplugged_probe_value: 0 # default
    battery_level:
      name: "IGrill v3 battery"
    temperature_probe1:
      name: "IGrill v3 temp 1"
    temperature_probe2:
      name: "IGrill v3 temp 2"
    temperature_probe3:
      name: "IGrill v3 temp 3"
    temperature_probe4:
      name: "IGrill v3 temp 4"
    propane_level:
      name: "IGrill v3 Propane"
  
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "IGrill WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "IGrill WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    
 binary_sensor:
  - platform: status
    name: "iGrill Adapter Status"
    entity_category: "diagnostic"
